// Project data
export const projects = {
  newspaper: [
    {
      id: 1,
      name: "Kalbela News Clone",
      description: "Kalbela News is an online news portal providing the latest updates on current affairs, politics, business, and more.",
      image: "/images/kalbelaNews.png",
      liveLink: "https://kalbela-news.vercel.app/",
      category: "Newspaper/Magazine",
    },
    {
      id: 2,
      name: "Jago News Clone",
      description: "Jago News is an online news portal delivering the latest headlines, current events, and in-depth coverage of national and international news.",
      image: "/images/jagoNews.png",
      liveLink: "https://jagonews.vercel.app/",
      category: "Newspaper/Magazine",
    },
    {
      id: 3,
      name: "Dhaka News Clone",
      description: "Dhaka News is an online platform offering up-to-date news, articles, and reports about Dhaka and the surrounding areas.",
      image: "/images/dhakaNews.png",
      liveLink: "https://dhaka-news.vercel.app/",
      category: "Newspaper/Magazine",
    },
    {
      id: 4,
      name: "News Times",
      description: "News Times is an online news platform providing timely updates and in-depth analysis on current events, global news, and more.",
      image: "/images/timeNews.png",
      liveLink: "https://news-times-liard.vercel.app/",
      category: "Newspaper/Magazine",
    },
    {
      id: 5,
      name: "Search BD News",
      description:
        "Search BD News is an online news platform providing the latest updates on local, national, and international news, covering various topics like politics, business, and entertainment.",
      image: "/images/searchBDnews.jpg",
      liveLink: "https://searchbdnews.com/",
      category: "Newspaper/Magazine",
    },
    {
      id: 6,
      name: "Bangladesh Alo NewsPaper",
      description:
        "Banglar Alo 24 is an online news platform providing the latest updates on local, national, and international news, with a focus on politics, entertainment, and more.",
      image: "/images/bangladeshAloNewsPaper.jpg",
      liveLink: "https://banglaralo24.com/",
      category: "Newspaper",
    },
    {
      id: 7,
      name: "People's News BD",
      description: "People's News BD is an online news platform delivering the latest updates on politics, current events, and local news from Bangladesh.",
      image: "/images/pepoleNews.jpg",
      liveLink: "https://www.peoplesnewsbd.com/",
      category: "Newspaper",
    },
  ],
  portfolio: [
    {
      id: 1,
      name: "Personal Blog Website",
      description: "Shawon Solaiman is a personal blog website where the author shares insights, experiences, and creative content on various topics.",
      image: "/images/personalBlog.jpg",
      liveLink: "https://shawonsolaiman.com/",
      category: "Custom Website",
    },
  ],
  ecommerce: [
    {
      id: 1,
      name: "Digital Solutions Ltd Store",
      description: "Digital Solutions Ltd's online store offers various digital products and services, including web development, software, and design solutions.",
      image: "/images/outeq.png",
      liveLink: "https://shop.digitalsolutions.ltd/",
      category: "E-Commerce",
    },
    {
      id: 2,
      name: "OVS Lifestyle",
      description: "OVS Lifestyle is an e-commerce website offering a variety of lifestyle products, including fashion and accessories.",
      image: "/images/lifestyle.png",
      liveLink: "https://ovs-lifestyle.vercel.app/",
      category: "E-Commerce",
    },
    {
      id: 3,
      name: "Kaca Bazar",
      description: "Kaca Bazar is an e-commerce platform offering fresh groceries and daily essentials for online shopping.",
      image: "/images/kacaBazar.png",
      liveLink: "https://kacabazar-xyz.vercel.app/",
      category: "E-Commerce",
    },
  ],
  business: [
    {
      id: 1,
      name: "Kalbela Jobs",
      description: "Kalbela Jobs is a job portal that connects job seekers with employers, providing various employment opportunities.",
      image: "/images/kalbelaJobs.png",
      liveLink: "https://kalbelajobs.com/",
      category: "Job Portal",
    },
    {
      id: 2,
      name: "Office Management Software",
      description: "Kalbela is an office management software designed to streamline administrative tasks, manage workflows, and improve productivity for businesses.",
      image: "/images/officeManagment.jpg",
      liveLink: "https://kalbela.info/",
      category: "Business",
    },
    {
      id: 3,
      name: "Cloud POS Software",
      description: "Cloud POS Software is an online platform offering point-of-sale (POS) solutions for businesses to manage sales, inventory, and transactions efficiently.",
      image: "/images/cloudPOS.jpg",
      liveLink: "https://pos.digitalsolutions.ltd/",
      category: "Business",
    },
    {
      id: 4,
      name: "Meta Clipping Studio Gallery",
      description: "Meta Clipping Studio Gallery showcases a collection of professional image editing and clipping path services.",
      image: "/images/cliphPath.png",
      liveLink: "https://meta-clipping-studio.vercel.app/gallery",
      category: "Business",
    },
    {
      id: 5,
      name: "RA Overseas Ltd",
      description: "RA Overseas Ltd is a business website providing overseas job recruitment and consultancy services.",
      image: "/images/overseas.png",
      liveLink: "https://ra-overseas-ltd.vercel.app/",
      category: "Business",
    },
    {
      id: 6,
      name: "DSM Visa Card",
      description: "DSM Visa Card is a website offering services related to visa card applications, payment solutions, and financial services for global transactions.",
      image: "/images/DSMVISACard.jpg",
      liveLink: "http://www.dsmvisacard.com/",
      category: "Business",
    },
    {
      id: 7,
      name: "ZAAG Systems INC",
      description: "ZSI AI is a company specializing in artificial intelligence solutions, offering AI-driven tools and services to enhance business processes and innovation.",
      image: "/images/zaakSystem.jpg",
      liveLink: "https://www.zsi.ai/",
      category: "Business",
    },
    {
      id: 8,
      name: "Cure SMA Bangladesh",
      description:
        "Cure SMA Bangladesh is a non-profit organization dedicated to raising awareness and supporting individuals and families affected by Spinal Muscular Atrophy (SMA) in Bangladesh.",
      image: "/images/cureSMABangladesh.jpg",
      liveLink: "https://curesmabangladesh.org/",
      category: "Business",
    },
    {
      id: 9,
      name: "Event Management",
      description: "Platform for organizing and promoting events with ticketing integration.",
      image: "/placeholder.svg?height=300&width=500",
      liveLink: "#",
      category: "NGO/Event/Education",
    },
    {
      id: 10,
      name: "Im Foru Org",
      description: "IMForU is a non-profit organization focused on providing resources, support, and empowerment to underserved communities and individuals.",
      image: "/images/imforu.jpg",
      liveLink: "http://imforu.org/",
      category: "Business",
    },
  ],
  custom: [
    {
      id: 1,
      name: "Football Hub",
      description: "Football Hub is a website dedicated to the latest football news, match updates, player stats, and in-depth analysis of the football world.",
      image: "/images/kingstar.png",
      liveLink: "https://your-football-website.com",
      category: "Custom Website",
    },
  ],
};

// Plans data with BDT pricing and per project model
export const plans = [
  {
    id: "basic",
    name: "Basic",
    price: 15000,
    features: ["Responsive website design", "5 pages included", "Basic SEO optimization", "Contact form integration", "Mobile-friendly design", "1 month free support"],
    cta: "Get Started",
    popular: false,
    color: "from-sky-600 to-blue-600",
  },
  {
    id: "professional",
    name: "Professional",
    price: 30000,
    features: [
      "Everything in Basic",
      "Custom design & branding",
      "Up to 10 pages",
      "Advanced SEO package",
      "Content management system",
      "Social media integration",
      "3 months free support",
    ],
    cta: "Best Value",
    popular: true,
    color: "from-sky-600 to-blue-600",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 60000,
    features: [
      "Everything in Professional",
      "E-commerce functionality",
      "Custom web application",
      "Database integration",
      "API development",
      "Advanced analytics",
      "Priority support",
      "6 months free support",
    ],
    cta: "Contact Us",
    popular: false,
    color: "from-sky-600 to-blue-600",
  },
];
